name: Publish Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout the repo
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: parsajr/fourequalsten
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy_on_server:
    name: Deploy Docker image to server
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      -
        name: Execute deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          usename: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            bash /home/fourequalsten/update.sh
